### ISSUE TITLE
use_static also sets contentroot?

### ISSUE THREAD

**Issue by NinoFloris** [SaturnFramework/Saturn#66]
`use_static` breaks resolving of things like configs which are copied by msbuild to be next to the project dll.

This search path is set through `ContentRoot(path)` which is basically asp.nets version of the CWD  (if you don't override it) and has very little to do with where your static files are served from which uses webroot.

I'd like to see it go :)

**Comment by Krzysztof-Cieslak** [comment]
As far as I remember this was done (or suggested) by @isaacabraham. Isaac, do you remember why we added that?

**Comment by isaacabraham** [comment]
Yeah, it was because the static hosting previously was having to be done "manually" as a route - it also didn't work when hosting through Azure App Service (and I'm sure that that's not a fault with App Service, but rather a symptom of the problem).

See #46 and the link inside it on docs msdn.

Happy to come up with an alternative solution but I thought that this looked like the official way to serve static content.

**Comment by NinoFloris** [comment]
@isaacabraham that change just adds UseDefaultFiles right? content root is older it's in https://github.com/SaturnFramework/Saturn/commit/b6b6e4bcd0df2ddd7896468222e881f3d7db4e5b

**Comment by isaacabraham** [comment]
Yeah, that's right. In that case this isn't to do with me then - not sure what ContentRoot does etc..

**Comment by NinoFloris** [comment]
Ok then I'd like to see it tagged as a bug, if something comes up and we have to revert we'll then have a record of why it was done.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by 832643fac84642a755b071bcf4ce1e8c916c1985
