### ISSUE TITLE
[Discussion] Unintuitive ordering of plugs

### ISSUE THREAD

**Issue by NinoFloris** [SaturnFramework/Saturn#72]
Unintuitive ordering of plugs, in my mind it would make more sense to have first plugs run first instead of last.

**Comment by Krzysztof-Cieslak** [comment]
Oh, if that’s the case than it’s bug

**Comment by NinoFloris** [comment]
Alright, https://github.com/NinoFloris/Saturn/blob/dbe095c8deecaa08fe26063d4228661bcd586f2a/src/Saturn/Controller.fs#L72
needs a flip for `>=>` then

**Comment by rmunn** [comment]
Left a comment on the wrong version of the commit, so it might not be visible to others. I'll reproduce it here:

As a matter of style preference, I'd rather see this written using `List.fold`. For example, the `Application.fs` code change would look like this:

```fsharp
let router = (state.Pipelines |> List.fold (fun acc e -> e >=> acc) succeed) >=> router
```

I'd suggest the same thing (`List.fold` over `List.foldBack`) for the other two code changes in `Controller.fs` and `Router.fs` as well.

The advantage of using `List.fold` here over `List.foldBack` is simplicity: it's slightly easier to track what's happening with `List.fold` in your head when reading the code. (And the F# implementation is simpler as well).

The difference between the `List.foldBack` implementation in the PR as it stands, and the `List.fold` implementation that I'm suggesting, would be the order in which composition happens: left-to-right or right-to-left. An example of what I mean is probably best: say you have an application which pipes requests through three different pipelines:

```fsharp
let app = application {
    pipe_through pipeA
    pipe_through pipeB
    pipe_through pipeC
}
```

From this CE, the `application` CE builder produces a list of pipelines `[C; B; A]`. The `foldBack` implementation suggested here would then compose these pipelines in the following order:

```text
succeed >=> A
(succeed >=> A) >=> B
((succeed >=> A) >=> B) >=> C
(((succeed >=> A) >=> B) >=> C) >=> router
```

The `List.fold` implementation I'm suggesting, OTOH, would compose the pipelines as follows:

```text
C >=> succeed
B >=> (C >=> succeed)
A >=> (B >=> (C >=> succeed))
(A >=> (B >=> (C >=> succeed))) >=> router
```

As long as the end-user has not created pipelines that have side effects when evaluated, then the order of composition shouldn't matter and the `List.fold` implementation wins on principles of simplicity. But if end users create pipelines with side effects somehow, then it might be important to let those side effects happen in the same order that the pipelines are declared in the source file. If that's an important design goal, then the way @NinoFloris wrote this PR is good because it will trigger the side effects of pipeline `A` before the side effects of pipeline `B` are triggered. (Those side effects will, of course, only be triggered once, which will probably surprise the end-user: anyone who creates pipelines with side effects has probably not fully understood the functional approach yet. And if they then specify `use_warbler`, their side effects won't be triggered at compose time and there will be no difference between the `List.fold` and `List.foldBack` approaches).

P.S. This comment came out more complicated than I was expecting; I hope I have been able to be clear.

**Comment by Krzysztof-Cieslak** [comment]
While pipelines should use warbler for most side effects, if someone really desires to do side effect on the composition (I don't have any example why someone would want to do it, but let's just assume it's possible) then having them executed in order of declaration sounds correct - i.e. following principle of least surprise. So I'm ok with keeping current implementation since it's not too much complex, and kinda supports this super weird edge case.
