### ISSUE TITLE
Investigate adding package for Turbolinks integration

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SaturnFramework/Saturn#94]
https://github.com/turbolinks/turbolinks

Rails version - https://github.com/turbolinks/turbolinks-rails

**Comment by NinoFloris** [comment]
Hmm how does this fit well with the SAFE stack of client side rendering?
(We actually use this in production by the way, but for a very hybrid app)

**Comment by isaacabraham** [comment]
You would probably just have a "cut down" SAFE stack I imagine? Potentially the S and A elements but probably would not have any client side code?

**Comment by Krzysztof-Cieslak** [comment]
Please remember that while Saturn is part of the SAFE stack users may want to use it just for server side (including server side rendering and some small JS components [that may or may not be written in Fable]), and I want to have good options for both use cases.

**Comment by NinoFloris** [comment]
Cool, that's a good clarification on Saturn's goals!

**Comment by isaacabraham** [comment]
I imagine something of interest to many people would be to see if / how it would be possible to combine this sort of library / "server-side-first" rendering, with the ability to "opt in" for client-side F# as well. Sort of like the good old ASP .NET MVC + Javascript days ;-)

**Comment by NinoFloris** [comment]
@isaacabraham So we actually do this succesfully with Vue + turbolinks glue on the frontend, then on the backend we use standard mvc razor with quite some extra taghelpers for backend to frontend component transformation, like form fields.

This all gives an amazingly smooth experience for both users and devs.

We mainly chose this over an api model as it's an admin panel. That means a lot of odd/one-off functionality where I'd rather have config/sensitive data not leak too easily, so server-side rendering is a better fit.

**Comment by isaacabraham** [comment]
@NinoFloris cool. Is this still using Fable? If so - I'm sure lots of people would be interested to see this!

**Comment by NinoFloris** [comment]
Nope it uses vue (vue.js) but it should carry over to something even more customizable like react without problems

**Comment by isaacabraham** [comment]
Sure - but it's surely possible to use vue.js with Fable I imagine. Either way from an architectural point of view, it's definitely interesting to see.

**Comment by rmunn** [comment]
I think that for people with no F# experience who are using C# ASP.NET and have some Javascript/Typescript experience, they could be persuaded to try Saturn for their ASP.NET setup due to its simplicity and declarative nature. But selling them on Fable seems like a harder sell if they already use Typescript: they'll feel (at least I'm pretty sure my colleagues would feel) like there's little benefit to learning an unfamiliar syntax (F#) just to write their Javascript code. "We already have Typescript and it works quite well," they'll say, "so why should we switch to Fable?" And the only major benefits of Fable that I can think of require you to already be invested in F# on the server side (sharing model code between server and client side, using nice familiar F# syntax for your Javascript, and so on).

So I like the idea of making server-only apps easier, as it seems to me that this will provide a smoother adoption path to the SAFE stack. Saturn first, then Fable once people have started to fall in love with F#.

**Comment by Krzysztof-Cieslak** [comment]
@Rfvgyhn, There is possibility to use both Razor or dotLiquid rendering - https://github.com/giraffe-fsharp/Giraffe.DotLiquid or https://github.com/giraffe-fsharp/Giraffe.Razor

**Comment by Rfvgyhn** [comment]
@Krzysztof-Cieslak Not sure how I missed that. Thanks. :)

**Comment by Krzysztof-Cieslak** [comment]
Fixed with #130
