### ISSUE TITLE
`use_custom_oauth` discussion

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SaturnFramework/Saturn#96]
So, `use_custom_oauth` is left in the core Saturn library, and specific implementations (Google, GitHub) has been moved to `Saturn.Extensions.Authentication`.

1. Should it still be in Core?
2. Should it be named `use_custom_oauth` ? maybe something like `use_oauth` would be better?

**Comment by rmunn** [comment]
Some thoughts:

* I like the `use_oauth` name, but maybe it should be called `use_oauth_with_config` to reflect the pattern of the other, third-party implementations. (Or `useOAuthWithConfig`, of course).
* All the OAuth implementations have pretty much the same `ev.OnCreatingTicket` implementation. That seems like it would be useful to factor out into a helper method, so that anyone using the "basic" `useOAuthWithConfig` wouldn't have to reimplement the wheel.
* Actually, that brings up a thought. There could be a generic `useOAuth` operation that doesn't require passing a custom config. It would take as parameters not just the clientId/clientSecret/jsonToClaimsMap parameters that the other OAuth implementations take, but also a set of three URLs that define the authorization endpoint, token endpoint, and user information endpoint. Maybe passed in as a record type called `OAuthEndpointUrls` or something, since all three of them are related and form a natural grouping.
* Refresh tokens are a whole new subject that hasn't even been touched on in the existing implementations.
* I feel like `useOAuth` should stay in Core, because it's a very commonly-desired feature. Its documentation can then point to the Saturn.Extensions.Authentication package for specific implementations for Google, GitHub, and whatever else gets added. Without an operation like `useOAuth` in Core, I feel like the other OAuth implementations will be far less likely to be discovered.
